apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ms
#  annotations:
#    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
        - name: customer-ms
          image: ghcr.io/dargor94/customer-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: VAULT_TOKEN
              value: root
      imagePullSecrets:
        - name: regcred
